---
- name: ocs
  sync: true
  repo_link: "https://github.com/red-hat-storage/ocs-operator"
  branch: main
  remote_api_directory: api/v1
  local_api_directory: schemes/ocs/operatorv1
  replace_imports:
    - old: 'nbv1 "github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1"'
      new: 'nbv1 "github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/noobaa"'
    - old: '"github.com/noobaa/noobaa-operator/v5/pkg/apis/noobaa/v1alpha1"'
      new: 'v1alpha1 "github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/noobaa"'
    - old: '"github.com/rook/rook/pkg/apis/ceph.rook.io/v1"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/ceph.rook.io/v1"'

- name: rook
  sync: true
  repo_link: "https://github.com/rook/rook"
  branch: master
  remote_api_directory: pkg/apis/ceph.rook.io
  local_api_directory: schemes/ocs/ceph.rook.io
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/k8s.cni.cncf.io/v1"'
    - old: '"github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/nadutils"'
    - old: '"github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/objectbucket.io/v1alpha1"'
    - old: '"github.com/rook/rook/pkg/apis/ceph.rook.io"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/ceph.rook.io"'
    - old: '"github.com/libopenstorage/secrets"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/libopenstorage/secrets"'
    - old: '"github.com/libopenstorage/secrets/vault"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/libopenstorage/secrets/vault"'

- name: bucket
  sync: true
  repo_link: "https://github.com/kube-object-storage/lib-bucket-provisioner"
  branch: master
  remote_api_directory: pkg/apis/objectbucket.io
  local_api_directory: schemes/ocs/objectbucket.io
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/objectbucket.io"'

- name: provisioner
  sync: true
  repo_link: "https://github.com/kube-object-storage/lib-bucket-provisioner"
  branch: master
  remote_api_directory: pkg/provisioner/api
  local_api_directory: schemes/ocs/provisioner
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/objectbucket.io/v1alpha1"'

- name: nad
  sync: true
  repo_link: "https://github.com/k8snetworkplumbingwg/network-attachment-definition-client"
  branch: master
  remote_api_directory: pkg/apis/k8s.cni.cncf.io
  local_api_directory: schemes/ocs/k8s.cni.cncf.io
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/k8s.cni.cncf.io"'

- name: nad
  sync: true
  repo_link: "https://github.com/k8snetworkplumbingwg/network-attachment-definition-client"
  branch: master
  remote_api_directory: pkg/utils
  local_api_directory: schemes/ocs/nadutils
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/k8s.cni.cncf.io/v1"'
    # Since replace_imports does not actually check for imports, just does a
    # find and replace, we can use it to fix this vet error in go 1.24+.
    - old: "fmt.Errorf(fmt.Sprintf(\"Failed to parse: one or more items did not match comma-delimited format (must consist of lower case alphanumeric characters). Must start and end with an alphanumeric character), mismatch @ '%v'\", allItems[i]))"
      new: "fmt.Errorf(\"Failed to parse: one or more items did not match comma-delimited format (must consist of lower case alphanumeric characters). Must start and end with an alphanumeric character), mismatch @ '%v'\", allItems[i])"

- name: noobaa-operator
  sync: true
  repo_link: "https://github.com/noobaa/noobaa-operator"
  branch: master
  remote_api_directory: pkg/apis/noobaa/v1alpha1
  local_api_directory: schemes/ocs/noobaa
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/kube-object-storage/lib-bucket-provisioner/pkg/apis/objectbucket.io/v1alpha1"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/objectbucket.io/v1alpha1"'
    - old: '"github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner/api"'
      new: api "github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/provisioner"

- name: secret
  sync: true
  repo_link: "https://github.com/libopenstorage/secrets"
  branch: master
  remote_api_directory: secrets.go
  local_api_directory: schemes/ocs/libopenstorage/secrets/secrets.go

- name: secret
  sync: true
  repo_link: "https://github.com/libopenstorage/secrets"
  branch: master
  remote_api_directory: secrets_manager.go
  local_api_directory: schemes/ocs/libopenstorage/secrets/secrets_manager.go

- name: secret
  sync: true
  repo_link: "https://github.com/libopenstorage/secrets"
  branch: master
  remote_api_directory: vault
  local_api_directory: schemes/ocs/libopenstorage/secrets/vault
  excludes:
    - "*test.go"
  replace_imports:
    - old: '"github.com/libopenstorage/secrets"'
      new: '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/libopenstorage/secrets"'
    - old: '"github.com/libopenstorage/secrets/vault/utils"'
      new:  '"github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/libopenstorage/secrets/vault/utils"'
...
